AllCops:
  Exclude:
    - bin/*
    - scripts/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - postqueue.gemspec

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# Try to keep numbers down:

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

# TODO: enable later
Style/StringLiterals:
  Enabled: false

# TODO: Remove once code is fixed
Style/RescueStandardError:
  Exclude:
#    - spec/postqueue/concurrency_spec.rb
#    - lib/postqueue/queue/processing.rb
