#!/bin/sh

if [ ! -z $GITHUB_WORKFLOW ]
  echo 'Setting a PGPASSWORD when running in GH action with DB PW'
  export PGPASSWORD='postgres'
fi


cat << SQL | psql -U postgres
CREATE ROLE postqueue PASSWORD 'postqueue' LOGIN;
SQL

cat << SQL | psql -U postgres
CREATE DATABASE postqueue_test WITH OWNER postqueue;
SQL

cat << SQL | psql -U postgres
CREATE DATABASE postqueue WITH OWNER postqueue
SQL
